# Generated by Django 5.2.8 on 2025-11-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_post_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateField(default='2025-11-25'),
        ),
    ]
